### ISSUE TITLE
Package file cannot be unzipped

### ISSUE THREAD

**Issue by KT1011** [cytsai/instant-espresso#1]
Hi,

I'd like to try your package but I met some problems. The refnet.pkl.zip provided from the web page cannot be unzipped. Can you provide an accessible network file again so that I can try the package. Thanks a lot!

**Comment by cytsai** [comment]
Hi @KT1011, can you check if the md5sum of your file is correct? It should be d19d1800a3f4560cb1546d91b253f7d3, or the exact file size should be 296,951,141 bytes. If they don't match, that means your file was not downloaded successfully. Try to download again from Dropbox, or [here](https://drive.google.com/file/d/0B8LpM_21I0tYLVBSN0NoU0w3b1U/view?usp=sharing). I don't think it's OS or unzip software dependent, but let me know if you still see problems.

**Comment by KT1011** [comment]
Hi @cytsai, the link you provided here is ok for me. I'm able to unzip it this time. Thanks a lot.
